// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/tenants": {
            "get": {
                "description": "Retrieves a list of tenants.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tenants"
                ],
                "summary": "List tenants",
                "responses": {
                    "200": {
                        "description": "List of tenants",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlertenant.TenantResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a basic tenant identity and triggers asynchronous provisioning.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tenants"
                ],
                "summary": "Create a new tenant",
                "parameters": [
                    {
                        "description": "Tenant creation data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlertenant.CreateTenantRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Tenant created (pending provisioning)",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.TenantResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Slug already exists",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tenants/id/{id}": {
            "get": {
                "description": "Retrieves a tenant's details using its UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tenants"
                ],
                "summary": "Get tenant by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tenant found",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.TenantResponse"
                        }
                    },
                    "404": {
                        "description": "Tenant not found",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tenants/slug/{slug}": {
            "get": {
                "description": "Retrieves a tenant's details using its slug.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tenants"
                ],
                "summary": "Get tenant by slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant Slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tenant found",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.TenantResponse"
                        }
                    },
                    "404": {
                        "description": "Tenant not found",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tenants/{id}": {
            "put": {
                "description": "Updates a tenant's name and description.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tenants"
                ],
                "summary": "Update a tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated tenant data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlertenant.UpdateTenantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tenant updated",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.TenantResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Tenant not found",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Soft deletes a tenant by its UUID.",
                "tags": [
                    "Tenants"
                ],
                "summary": "Delete a tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Tenant deleted"
                    },
                    "404": {
                        "description": "Tenant not found",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlertenant.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlertenant.CreateTenantRequest": {
            "description": "Tenant creation request data",
            "type": "object",
            "required": [
                "name",
                "owner_id"
            ],
            "properties": {
                "description": {
                    "description": "Optional description",
                    "type": "string",
                    "example": "This is the main tenant for my company"
                },
                "name": {
                    "description": "Tenant display name",
                    "type": "string",
                    "example": "My Awesome Corp"
                },
                "owner_id": {
                    "type": "string",
                    "example": "018d867c-3f41-71fb-89c5-34821cc6bd6d"
                },
                "slug": {
                    "description": "Unique slug, will be generated from name if empty",
                    "type": "string",
                    "example": "my-awesome-corp"
                }
            }
        },
        "handlertenant.ErrorResponse": {
            "description": "Error details",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid request data"
                },
                "message": {
                    "type": "string",
                    "example": "the name field is required"
                }
            }
        },
        "handlertenant.TenantResponse": {
            "description": "Tenant response data",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-02-07T12:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "This is the main tenant for my company"
                },
                "id": {
                    "type": "string",
                    "example": "018d867c-3f41-71fb-89c5-34821cc6bd6d"
                },
                "name": {
                    "type": "string",
                    "example": "My Awesome Corp"
                },
                "slug": {
                    "type": "string",
                    "example": "my-awesome-corp"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/tenantmodel.StatusType"
                        }
                    ],
                    "example": "pending"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-02-07T12:00:00Z"
                }
            }
        },
        "handlertenant.UpdateTenantRequest": {
            "description": "Tenant update request data",
            "type": "object",
            "required": [
                "name",
                "owner_id"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Updated description"
                },
                "name": {
                    "type": "string",
                    "example": "Updated Corp Name"
                },
                "owner_id": {
                    "type": "string",
                    "example": "018d867c-3f41-71fb-89c5-34821cc6bd6d"
                }
            }
        },
        "tenantmodel.StatusType": {
            "type": "string",
            "enum": [
                "pending",
                "active",
                "inactive",
                "suspended"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusActive",
                "StatusInactive",
                "StatusSuspended"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8443",
	BasePath:         "/",
	Schemes:          []string{"https"},
	Title:            "Lockari Vault Control Plane API",
	Description:      "API for managing tenants and core infrastructure.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
